/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Component;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JLabel;

/**
 *
 * @author Aragao
 */
public class TelaPrincipal extends javax.swing.JFrame {
    TelaClientes tc;
    TelaProduto tp;
    TelaCadastroCliente tcc;
    TelaCadastroProduto tcp;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH);
    }

    private void removeDesktopAll(){
        jDesktopPane1.removeAll();
        jDesktopPane1.setEnabled(false);
        jDesktopPane1.setEnabled(true);
        /*for (Component c:jDesktopPane1.getComponents()){
            c.setVisible(false);
        }*/
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        jMenuPopUpColor = new javax.swing.JMenu();
        jMenuItemPopUpAzul = new javax.swing.JMenuItem();
        jMenuItemPopUpVermelho = new javax.swing.JMenuItem();
        jMenuItemPopUpRosa = new javax.swing.JMenuItem();
        jMenuItemPopUpVerde = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelData = new javax.swing.JLabel();
        jLabelUsuTipo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNovo = new javax.swing.JMenu();
        jMenuItemNovoCom = new javax.swing.JMenuItem();
        jMenuItemNovoCli = new javax.swing.JMenuItem();
        jMenuItemNovoPro = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemListCli = new javax.swing.JMenuItem();
        jMenuItemListPro = new javax.swing.JMenuItem();
        jMenuGerar = new javax.swing.JMenu();
        jMenuItemGerarPlan = new javax.swing.JMenuItem();
        jMenuItemGerarGraf = new javax.swing.JMenuItem();
        jMenuExcluir = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuInfo = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        jMenuPopUpColor.setText("Cor do Plano de Fundo");
        jMenuPopUpColor.setToolTipText("");
        jMenuPopUpColor.setActionCommand("");

        jMenuItemPopUpAzul.setText("Azul");
        jMenuItemPopUpAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPopUpAzulActionPerformed(evt);
            }
        });
        jMenuPopUpColor.add(jMenuItemPopUpAzul);

        jMenuItemPopUpVermelho.setText("Vermelho");
        jMenuItemPopUpVermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPopUpVermelhoActionPerformed(evt);
            }
        });
        jMenuPopUpColor.add(jMenuItemPopUpVermelho);

        jMenuItemPopUpRosa.setText("Rosa");
        jMenuItemPopUpRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPopUpRosaActionPerformed(evt);
            }
        });
        jMenuPopUpColor.add(jMenuItemPopUpRosa);

        jMenuItemPopUpVerde.setText("Verde");
        jMenuItemPopUpVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPopUpVerdeActionPerformed(evt);
            }
        });
        jMenuPopUpColor.add(jMenuItemPopUpVerde);

        jPopupMenu.add(jMenuPopUpColor);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(51, 255, 51));
        jDesktopPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDesktopPane1MouseReleased(evt);
            }
        });

        jLabelData.setText("jLabel1");

        jLabelUsuTipo.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelData, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelUsuTipo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsuTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 628, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 384, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuNovo.setText("Novo");

        jMenuItemNovoCom.setText("Compra");
        jMenuNovo.add(jMenuItemNovoCom);

        jMenuItemNovoCli.setText("Cliente");
        jMenuItemNovoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoCliActionPerformed(evt);
            }
        });
        jMenuNovo.add(jMenuItemNovoCli);

        jMenuItemNovoPro.setText("Produto");
        jMenuItemNovoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoProActionPerformed(evt);
            }
        });
        jMenuNovo.add(jMenuItemNovoPro);

        jMenuBar1.add(jMenuNovo);

        jMenu1.setText("Listar");

        jMenuItemListCli.setText("Clientes");
        jMenuItemListCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListCliActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemListCli);

        jMenuItemListPro.setText("Produtos");
        jMenuItemListPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListProActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemListPro);

        jMenuBar1.add(jMenu1);

        jMenuGerar.setText("Gerar");

        jMenuItemGerarPlan.setText("Planilha");
        jMenuGerar.add(jMenuItemGerarPlan);

        jMenuItemGerarGraf.setText("Gráfico");
        jMenuGerar.add(jMenuItemGerarGraf);

        jMenuBar1.add(jMenuGerar);

        jMenuExcluir.setText("Excluir");
        jMenuExcluir.setEnabled(false);

        jMenuItem4.setText("Cliente");
        jMenuExcluir.add(jMenuItem4);

        jMenuItem7.setText("Produto");
        jMenuExcluir.add(jMenuItem7);

        jMenuBar1.add(jMenuExcluir);

        jMenuInfo.setText("Info");

        jMenuItemSobre.setText("Sobre");
        jMenuInfo.add(jMenuItemSobre);

        jMenuBar1.add(jMenuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setBounds(0, 0, 744, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNovoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoCliActionPerformed
        //removeDesktopAll();
        tcc = new TelaCadastroCliente();
        jDesktopPane1.add(tcc);
        tcc.setVisible(true);
    }//GEN-LAST:event_jMenuItemNovoCliActionPerformed

    private void jMenuItemNovoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoProActionPerformed
        //removeDesktopAll();
        jDesktopPane1.removeAll();
        tcp = new TelaCadastroProduto();
        jDesktopPane1.add(tcp);
        tcp.setVisible(true);
    }//GEN-LAST:event_jMenuItemNovoProActionPerformed

    private void jDesktopPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane1MouseReleased
        if(evt.isPopupTrigger()){
            jPopupMenu.show(this, evt.getXOnScreen(), evt.getYOnScreen());
        }
    }//GEN-LAST:event_jDesktopPane1MouseReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        jLabelData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItemPopUpAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPopUpAzulActionPerformed
        jDesktopPane1.setBackground(Color.BLUE);
    }//GEN-LAST:event_jMenuItemPopUpAzulActionPerformed

    private void jMenuItemPopUpVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPopUpVermelhoActionPerformed
        jDesktopPane1.setBackground(Color.RED);
    }//GEN-LAST:event_jMenuItemPopUpVermelhoActionPerformed

    private void jMenuItemPopUpRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPopUpRosaActionPerformed
        jDesktopPane1.setBackground(Color.PINK);
    }//GEN-LAST:event_jMenuItemPopUpRosaActionPerformed

    private void jMenuItemPopUpVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPopUpVerdeActionPerformed
        jDesktopPane1.setBackground(Color.GREEN);
    }//GEN-LAST:event_jMenuItemPopUpVerdeActionPerformed

    private void jMenuItemListProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListProActionPerformed
        tp = new TelaProduto();
        jDesktopPane1.add(tp);
        tp.setVisible(true);
    }//GEN-LAST:event_jMenuItemListProActionPerformed

    private void jMenuItemListCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListCliActionPerformed
        tc = new TelaClientes();
        jDesktopPane1.add(tc);
        tc.setVisible(true);
    }//GEN-LAST:event_jMenuItemListCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    public void setjLabelUsuTipo(String jLabelUsuTipo) {
        this.jLabelUsuTipo.setText(jLabelUsuTipo);
    }

    public JLabel getjLabelUsuTipo() {
        return jLabelUsuTipo;
    }

    public void setjLabelUsuTipo(JLabel jLabelUsuTipo) {
        this.jLabelUsuTipo = jLabelUsuTipo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelUsuTipo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenu jMenuExcluir;
    private javax.swing.JMenu jMenuGerar;
    private javax.swing.JMenu jMenuInfo;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemGerarGraf;
    private javax.swing.JMenuItem jMenuItemGerarPlan;
    private javax.swing.JMenuItem jMenuItemListCli;
    private javax.swing.JMenuItem jMenuItemListPro;
    private javax.swing.JMenuItem jMenuItemNovoCli;
    private javax.swing.JMenuItem jMenuItemNovoCom;
    private javax.swing.JMenuItem jMenuItemNovoPro;
    private javax.swing.JMenuItem jMenuItemPopUpAzul;
    private javax.swing.JMenuItem jMenuItemPopUpRosa;
    private javax.swing.JMenuItem jMenuItemPopUpVerde;
    private javax.swing.JMenuItem jMenuItemPopUpVermelho;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuNovo;
    private javax.swing.JMenu jMenuPopUpColor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu;
    // End of variables declaration//GEN-END:variables
}
